### ISSUE TITLE
Why is `account` getting appended here?

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-web-profile#3]
Why is `account` getting appended here?

It should not be being appended.  Need to clean this up later.

_Originally posted by @dlongley in https://github.com/digitalbazaar/bedrock-web-profile/pull/2_

**Comment by aljones15** [comment]
Original Comment:

https://github.com/digitalbazaar/bedrock-web-profile/pull/2#discussion_r388569032

This now applies to this line:

https://github.com/digitalbazaar/bedrock-web-profile/blob/5b4aee41765cd5790601b0052a10a56b554f8b34/ProfileService.js#L241

in the method:

https://github.com/digitalbazaar/bedrock-web-profile/blob/5b4aee41765cd5790601b0052a10a56b554f8b34/ProfileService.js#L229-L251

At the time this comment was made `account` was not being escaped by `encodeUriComponent`.

This in turn calls on a delete API endpoint not defined in [`bedrock-profile-http`](https://github.com/digitalbazaar/bedrock-profile-http/blob/master/lib/http.js)

Just to prevent confusion: The POST endpoint for `capability-set` does accept an account query: 

https://github.com/digitalbazaar/bedrock-profile-http/blob/bd8977c3a3922fc5019349f850db590730f61399/lib/http.js#L230-L241

**Comment by dlongley** [comment]
This has been cleaned up, closing.
