### ISSUE TITLE
Structure of bedrock-web modules

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-web-profile#7]
commingling code with other stuff on the root of modules makes it difficult to configure a linting script.  Is there are reason we did not setup a `lib` or `src` folder as with other libs?

Would there be any objection to setting up such a folder structure now as we setup CI etc?

**Comment by dlongley** [comment]
We should probably just adopt `lib` across all modules and have the same structure everywhere, including BSD-3 ones. This shouldn't affect top-level applications (which may need to be different).

**Comment by dlongley** [comment]
The goal is also to start moving toward using ES modules everywhere, including node.js only modules.  We should have a common pattern using the `esm` npm module to fill any gaps until we can remove it in the future.

**Comment by dlongley** [comment]
A `lib` directory is now being used with PR #18, closing.
