### ISSUE TITLE
FIXME Count 2

### ISSUE THREAD

**Issue by mandyvenables** [digitalbazaar/bedrock-web-profile#9]
- [ ] FIXME: there may be better wrappers already created
       Commit: (47629c1) Add core files.
       File:  [ProfileService.js:258](https://github.com/digitalbazaar/bedrock-web-profile/blob/master/ProfileService.js#L258)
       Matthew Collier commented 4 months ago

  - [ ] * @param {string} [config.urls.base = 'FIXME']
       Commit: (47629c1) Add core files.
       File:  [ProfileService.js:15](https://github.com/digitalbazaar/bedrock-web-profile/blob/master/ProfileService.js#L15)
       Matthew Collier commented 4 months ago

       FIXME Count         2
       Oldest Comment      4 months ago
       Oldest Commenter    Matthew Collier
       Oldest Comment      FIXME: there may be better wrappers already created

**Comment by dlongley** [comment]
FIXMEs addressed/removed, closing.
